---
title: "Documento Técnico N°5: Medición de la contribución económica del turismo"
subtitle: "El turismo desde la perspectiva de la oferta: actividad y empleo" 
author: "Dirección Nacional de Mercados y Estadísticas -  Subsecretaría de Desarrollo Estratégico"
date: "`r format(Sys.Date(), format = '%d de %B de %Y')`"
site: bookdown::bookdown_site
documentclass: book
classoption: openany
bibliography: [book.bib, packages.bib]
csl: estudios-hispanicos.csl
link-citations: yes
description: "Medición de la contribución económica del turismo"
---

# Presentación {.unnumbered}

El presente documento, **Medición de la contribución económica del turismo: actividad y empleo**, se enmarca en el proyecto de Armonización de las Estadísticas de Turismo en las Provincias de la [Dirección Nacional de Mercados y Estadística de la Subsecretaría de Desarrollo Estratégico del Ministerio de Turismo y Deportes](http://datos.yvera.gob.ar/). El objetivo general de este proyecto es contribuir con propuestas metodológicas para los sistemas de estadísticas de turismo provinciales que orienten a producir indicadores provinciales básicos y comparables.

Además de este, se encuentra disponible una serie de documentos técnicos que abordan otras problemáticas vinculadas a la producción de estadística de turismo:

-   [Documento Técnico \#1](https://dnme-minturdep.github.io/DT1_medicion_turismo/): Conceptos y elementos básicos para la medición provincial de los turistas

-   [Documento Técnico \#2](https://dnme-minturdep.github.io/DT2_encuestas/): Propuestas metodológicas para las encuestas de ocupación en alojamientos turísticos

-   [Documento Técnico \#3](https://dnme-minturdep.github.io/DT3_registros_adminsitrativos/): Descripción, análisis y utilización de los Registros Administrativos para la medición del Turismo

-   [Documento Técnico \#4](https://dnme-minturdep.github.io/DT4_perfiles/): Propuestas Metodológicas para las Encuestas de Perfil del Visitante

### Documento Técnico Nº5 - Resumen {.unnumbered}

El objetivo general es describir las metodologías disponibles para elaborar indicadores de la actividad del turismo desde la perspectiva de oferta. En particular se analiza los desafíos de la medición de la contribución económica del turismo a la actividad y el empleo desde las distintas ópticas territoriales. En virtud de estos objetivos, este documento se estructura en tres capítulos.

En el **Capítulo** \@ref(medicion-actividad) se desarrolla una metodología, según las recomendaciones internacionales, para la medición de la contribución económica del turismo en un territorio. En sus diferentes secciones, presenta la definición y el alcance de las actividades económicas involucradas en el turismo a partir del enfoque de las Ramas Características, recomendaciones generales para la medición, indicadores macroeconómicos básicos que darán cuenta de la contribución desde la perspectiva de la oferta y antecedentes nacional e internacional del uso de esta perspectiva para la medición de la contribución económica del turismo en sus respectivos territorios de interés.


En el **Capítulo** \@ref(medicion-empleo) se desarrollan las problemáticas básicas al momento de medir el empleo en el sector turístico como parte del sistema económico. En sus diferentes secciones, presenta una síntesis sobre las definiciones básicas y las recomendaciones internacionales para la medición del empleo y los antecedentes internacionales y nacionales de medición del empleo en el sector turístico.

El **Capítulo** \@ref(fuentes-informacion) presenta las fuentes de información disponibles para la medición de la actividad y el empleo en ramas características del turismo a nivel provincial. Se describen los tipos de fuentes, sus principales características, ventajas y limitaciones. El capítulo se concentra en aquellas fuentes disponibles al público general, mostrando ejemplos de uso a partir de información reciente.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

knitr::opts_chunk$set(out.width = '100%', fig.align = 'center')
```

